### ISSUE TITLE
nameからwikipediaなどの結果を表示

### ISSUE THREAD

**Issue by tgib23** [tgib23/douzou_chan2#73]

**Comment by tgib23** [comment]
表示はしてないな

**Comment by satoshya** [comment]
ajax使って表示する方法取得しましょう

**Comment by tgib23** [comment]
Wikipedia clientで取得
post showでincludeして jsからget-wikipedia methodを呼び出して、その中でPostデータからwikipedia-nameがあれば表示するように記述かな。
もうちょっとスマートな呼び方ないか調べる
